#!/bin/bash

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║           Welcome to APIRE AI Security Platform              ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "🚀 Your environment is ready!"
echo ""
echo "🔗 Access your applications:"
echo "   - Core Dashboard:      http://localhost:5173"
echo "   - Prompt Shield:       http://localhost:3002"
echo "   - RedTeam Kit:         http://localhost:3006"
echo "   - Compliance Checker:  http://localhost:3004"
echo ""
echo "🛠️  Useful Commands:"
echo "   - Run Tests:           ./scripts/test-all.sh"
echo "   - Rebuild:             ./scripts/build.sh"
echo ""
echo "Happy Hacking! 🛡️"
echo ""
