#!/bin/bash
echo ""
echo "****************************************************************"
echo "*                                                              *"
echo "*        Welcome to Apire AI Security Platform!                *"
echo "*                                                              *"
echo "****************************************************************"
echo ""
echo "To start the entire platform, run:"
echo "   ./scripts/start-codespace.sh"
echo ""
echo "This will launch all microservices and frontends."
echo ""
